#!/usr/bin/env python3

from __future__ import annotations

import argparse
import json
import os
import sys
from dataclasses import dataclass
from datetime import datetime, timedelta, timezone
from pathlib import Path
from typing import Iterable
from urllib.error import HTTPError, URLError
from urllib.parse import urlencode
from urllib.request import Request, urlopen


REPO_ROOT = Path(__file__).resolve().parents[1]
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

try:
    import api_config as shared_api_config
except Exception:
    shared_api_config = None


DEFAULT_NEWS_QUERY = (
    '(AI OR "artificial intelligence" OR "generative AI" OR LLM OR '
    '"voice AI" OR "conversational AI" OR "AI agent")'
)
DEFAULT_NEWS_LANGUAGE = "en"
DEFAULT_NEWS_PAGE_SIZE = 100
DEFAULT_NEWS_MAX_PAGES = 1
DEFAULT_GROQ_MODEL = "llama-3.3-70b-versatile"
DEFAULT_MAX_ARTICLES_FOR_PROMPT = 30
MAX_TITLE_CHARS = 220
MAX_DESC_CHARS = 360
MAX_CONTENT_CHARS = 360

PROMPT_TEMPLATE = """the context that will be given is a persona profile and a set of projects they are currently working on make one up for the prompt (just do 1 project for this tata group employe - an ai voice agent that can call for a loan company - they are from tata capital) the output should be a general summary of the news (not contextualized) and then short suggestions on how each development or piece of news could help for the user Every insight generated by the LLM should retain a link to the original source article, paper, or announcement. it shouldn't summarize each article group it more by development or topic this a weekly update

Context
User Profile
Full Name: Puneet Agarwal
Company: Tata Capital
Department: Digital & AI Products
Job Title: Head of AI Product
Profile Summary: AI Product leader at Tata Capital with 11+ years across product management. Currently building voice agentic AI across the customer lifecycle - pre-sales, collections, and retention - in partnership with Sarvam. Passionate about turning frontier AI into compliant, high-impact products for BFSI.
AI Skills:
AI Product Management
Agentic AI
Voice AI
Conversational AI
Product Strategy
Active Project
AI Voice Agent for Loan Operations
An AI-powered voice agent capable of:
Calling prospective customers
Conducting loan eligibility screening
Answering product questions
Collecting application information
Following up on incomplete applications
Scheduling callbacks with human agents
Supporting collections and payment reminders
Current Status:
{In Progress}

Weekly AI Developments
{WEEKLY_AI_NEWS}

Task
Review all developments and identify the major themes, technological advancements, product launches, research breakthroughs, regulatory changes, and market trends.
Do not summarize articles individually.
Instead, group related developments into broader themes and explain what changed during the week.
For each theme:
Theme
Provide a concise title.
What Happened
Summarize the development across all relevant sources.
Why It Matters
Explain why the development is important in the broader AI landscape.
Potential Relevance to Current Project
Briefly explain how the development could potentially benefit, accelerate, improve, or influence the user's AI Voice Agent project.
Limit this section to 2-4 concise bullets.
Sources
List every source that contributed to the insight.
For each source include:
Article title
Publisher
URL

Final Output Structure
Executive Summary
A concise summary of the most important AI developments this week.
Major AI Developments
Theme 1
What Happened
Why It Matters
Potential Relevance to Current Project
Sources
Theme 2
What Happened
Why It Matters
Potential Relevance to Current Project
Sources
Theme 3
What Happened
Why It Matters
Potential Relevance to Current Project
Sources
(Continue as needed)
What To Watch Next
Identify emerging developments that may become important over the next 30-90 days.
Key Takeaways For The User
Provide 3-5 actionable observations related to the user's current project.
Keep recommendations practical and specific.

Critical Instructions
Group developments by topic, not by article.
Do not produce article-by-article summaries.
Maintain a neutral and factual tone.
Focus on developments from the current reporting period.
Every insight must include links to all supporting source articles.
If multiple articles discuss the same development, combine them into a single theme.
Spend approximately 70% of the output on explaining developments and 30% on project relevance.
Relevance suggestions should be concise and should not dominate the report.
Avoid generic statements such as "AI is growing rapidly" or "this could improve efficiency."
Make direct connections between the development and the user's project where possible.
"""


@dataclass
class Article:
    title: str
    source_name: str
    url: str
    published_at: str
    description: str
    content: str
    author: str


def optional_config_value(name: str) -> str:
    if shared_api_config is None:
        return ""
    return str(getattr(shared_api_config, name, "") or "").strip()


def get_api_key(env_name: str, config_name: str) -> str:
    return os.getenv(env_name, "").strip() or optional_config_value(config_name)


def fetch_json(url: str, headers: dict[str, str] | None = None, timeout: int = 60) -> dict:
    request = Request(
        url,
        headers=headers or {
            "Accept": "application/json",
            "User-Agent": "TataScraperTest/APITest/1.0",
        },
        method="GET",
    )

    try:
        with urlopen(request, timeout=timeout) as response:
            return json.loads(response.read().decode("utf-8"))
    except HTTPError as exc:
        error_body = exc.read().decode("utf-8", errors="replace").strip()
        message = f"HTTP error calling {url}: {exc.code} {exc.reason}"
        if error_body:
            message = f"{message}\n{error_body}"
        raise RuntimeError(message) from exc
    except URLError as exc:
        raise RuntimeError(f"Network error calling {url}: {exc.reason}") from exc


def fetch_news_articles(
    api_key: str,
    query: str,
    from_date: str,
    to_date: str,
    language: str,
    max_pages: int,
    page_size: int,
) -> list[Article]:
    articles: list[Article] = []
    news_headers = {
        "Accept": "application/json",
        "User-Agent": "TataScraperTest-APITest/1.0 (weekly-ai-news-reporter)",
        "X-Api-Key": api_key,
    }

    for page in range(1, max_pages + 1):
        params = {
            "q": query,
            "from": from_date,
            "to": to_date,
            "language": language,
            "sortBy": "publishedAt",
            "pageSize": page_size,
            "page": page,
        }
        url = f"https://newsapi.org/v2/everything?{urlencode(params)}"
        payload = fetch_json(url, headers=news_headers)

        status = payload.get("status")
        if status != "ok":
            raise RuntimeError(
                f"NewsAPI returned a non-ok response: {payload.get('code') or status} - "
                f"{payload.get('message') or 'Unknown error'}"
            )

        raw_articles = payload.get("articles", [])
        if not raw_articles:
            break

        for item in raw_articles:
            articles.append(
                Article(
                    title=(item.get("title") or "").strip(),
                    source_name=((item.get("source") or {}).get("name") or "").strip(),
                    url=(item.get("url") or "").strip(),
                    published_at=(item.get("publishedAt") or "").strip(),
                    description=(item.get("description") or "").strip(),
                    content=(item.get("content") or "").strip(),
                    author=(item.get("author") or "").strip(),
                )
            )

        total_results = int(payload.get("totalResults") or 0)
        if page * page_size >= min(total_results, max_pages * page_size):
            break

    return dedupe_articles(articles)


def dedupe_articles(articles: Iterable[Article]) -> list[Article]:
    seen: set[str] = set()
    deduped: list[Article] = []

    for article in articles:
        if not article.url or not article.title:
            continue
        key = article.url.lower().strip()
        if key in seen:
            continue
        seen.add(key)
        deduped.append(article)

    return deduped


def normalize_text(text: str) -> str:
    cleaned = " ".join((text or "").replace("\r", " ").replace("\n", " ").split())
    return cleaned.replace("[+", " [plus ").strip()


def truncate_text(text: str, limit: int) -> str:
    normalized = normalize_text(text)
    if len(normalized) <= limit:
        return normalized
    return normalized[: max(0, limit - 3)].rstrip() + "..."


def select_articles_for_prompt(articles: list[Article], limit: int) -> list[Article]:
    return articles[:limit]


def format_weekly_news(articles: list[Article]) -> str:
    if not articles:
        return "No matching articles were found for the reporting window."

    lines: list[str] = []
    for index, article in enumerate(articles, start=1):
        lines.extend(
            [
                f"Article {index}",
                f"Title: {truncate_text(article.title, MAX_TITLE_CHARS)}",
                f"Publisher: {normalize_text(article.source_name) or 'Unknown'}",
                f"Published At: {article.published_at or 'Unknown'}",
                f"URL: {article.url}",
                f"Description: {truncate_text(article.description, MAX_DESC_CHARS) or 'N/A'}",
                f"Content Snippet: {truncate_text(article.content, MAX_CONTENT_CHARS) or 'N/A'}",
                "",
            ]
        )
    return "\n".join(lines).strip()


def build_prompt(articles: list[Article]) -> str:
    prompt_articles = select_articles_for_prompt(articles, DEFAULT_MAX_ARTICLES_FOR_PROMPT)
    return PROMPT_TEMPLATE.replace("{WEEKLY_AI_NEWS}", format_weekly_news(prompt_articles))


def call_groq(prompt: str, api_key: str, model: str) -> str:
    payload = {
        "model": model,
        "messages": [{"role": "user", "content": prompt}],
        "temperature": 0.2,
    }

    request = Request(
        "https://api.groq.com/openai/v1/chat/completions",
        data=json.dumps(payload).encode("utf-8"),
        headers={
            "Authorization": f"Bearer {api_key}",
            "Content-Type": "application/json",
            "Accept": "application/json",
            "User-Agent": "TataScraperTest/APITest/1.0",
        },
        method="POST",
    )

    try:
        with urlopen(request, timeout=120) as response:
            body = json.loads(response.read().decode("utf-8"))
    except HTTPError as exc:
        error_body = exc.read().decode("utf-8", errors="replace").strip()
        message = f"Groq API error: {exc.code} {exc.reason}"
        if error_body:
            message = f"{message}\n{error_body}"
        raise RuntimeError(message) from exc
    except URLError as exc:
        raise RuntimeError(f"Network error calling Groq: {exc.reason}") from exc

    try:
        return body["choices"][0]["message"]["content"].strip()
    except (KeyError, IndexError, TypeError) as exc:
        raise RuntimeError(f"Unexpected Groq response format: {json.dumps(body, indent=2)}") from exc


def ensure_dir(path: Path) -> None:
    path.mkdir(parents=True, exist_ok=True)


def save_final_output(output_dir: Path, report: str) -> Path:
    ensure_dir(output_dir)
    report_path = output_dir / "weekly_update.md"
    report_path.write_text(report, encoding="utf-8")
    return report_path


def utc_now() -> datetime:
    return datetime.now(timezone.utc)


def default_date_window(days: int) -> tuple[str, str]:
    end = utc_now()
    start = end - timedelta(days=days)
    return start.isoformat(timespec="seconds"), end.isoformat(timespec="seconds")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Fetch last week's AI news from NewsAPI and create a grouped weekly update with Groq."
    )
    parser.add_argument(
        "--days",
        type=int,
        default=7,
        help="Number of trailing days to fetch from NewsAPI. Defaults to 7.",
    )
    parser.add_argument(
        "--query",
        default=DEFAULT_NEWS_QUERY,
        help="NewsAPI query string. Defaults to a broad AI news query.",
    )
    parser.add_argument(
        "--language",
        default=DEFAULT_NEWS_LANGUAGE,
        help="NewsAPI language filter. Defaults to en.",
    )
    parser.add_argument(
        "--max-pages",
        type=int,
        default=DEFAULT_NEWS_MAX_PAGES,
        help=f"Maximum NewsAPI pages to fetch. Defaults to {DEFAULT_NEWS_MAX_PAGES}.",
    )
    parser.add_argument(
        "--page-size",
        type=int,
        default=DEFAULT_NEWS_PAGE_SIZE,
        help="Page size per NewsAPI request. Defaults to 100.",
    )
    parser.add_argument(
        "--model",
        default=DEFAULT_GROQ_MODEL,
        help=f"Groq model to use. Defaults to {DEFAULT_GROQ_MODEL}.",
    )
    parser.add_argument(
        "--output-dir",
        default=str(Path(__file__).resolve().parent / "outputs"),
        help="Directory where the final Groq output will be saved.",
    )
    return parser.parse_args()


def validate_args(args: argparse.Namespace) -> None:
    if args.days <= 0:
        raise ValueError("--days must be greater than 0.")
    if args.max_pages <= 0:
        raise ValueError("--max-pages must be greater than 0.")
    if args.page_size <= 0 or args.page_size > 100:
        raise ValueError("--page-size must be between 1 and 100 for NewsAPI.")
    if args.max_pages * args.page_size > 100:
        raise ValueError(
            "NewsAPI developer accounts can fetch at most 100 results total. "
            "Reduce --max-pages or --page-size."
        )


def main() -> int:
    args = parse_args()

    try:
        validate_args(args)
        news_api_key = get_api_key("NEWS_API_KEY", "NEWS_API_KEY")
        if not news_api_key:
            raise RuntimeError("Missing NewsAPI key. Set NEWS_API_KEY in your environment or api_config.py.")

        groq_api_key = get_api_key("GROQ_API_KEY", "GROQ_API_KEY")
        if not groq_api_key:
            raise RuntimeError("Missing Groq key. Set GROQ_API_KEY in your environment or api_config.py.")

        from_date, to_date = default_date_window(args.days)
        articles = fetch_news_articles(
            api_key=news_api_key,
            query=args.query,
            from_date=from_date,
            to_date=to_date,
            language=args.language,
            max_pages=args.max_pages,
            page_size=args.page_size,
        )

        prompt = build_prompt(articles)
        report = call_groq(prompt=prompt, api_key=groq_api_key, model=args.model)
        output_root = Path(args.output_dir).resolve()
        saved_path = save_final_output(output_root, report)

        print(f"Fetched {len(articles)} article(s).")
        print(f"Weekly update saved to: {saved_path}")
        return 0
    except ValueError as exc:
        sys.stderr.write(f"{exc}\n")
    except RuntimeError as exc:
        sys.stderr.write(f"{exc}\n")
    except Exception as exc:
        sys.stderr.write(f"Unexpected error: {exc}\n")

    return 1


if __name__ == "__main__":
    raise SystemExit(main())
